/**
 * ActionDetection.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ImageSize from '../model/ImageSize';
import ObjectDetectionResponse from '../model/ObjectDetectionResponse';

/**
* ObjectDetection service.
* @module api/ObjectDetectionApi
* @version 1.0
*/
export default class ObjectDetectionApi {

    /**
    * Constructs a new ObjectDetectionApi. 
    * @alias module:api/ObjectDetectionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the objectDetectionDetectObjectsInCameraViewGet operation.
     * @callback module:api/ObjectDetectionApi~objectDetectionDetectObjectsInCameraViewGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectDetectionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.cameraIP 
     * @param {module:model/ImageSize} opts.imageSize 
     * @param {module:api/ObjectDetectionApi~objectDetectionDetectObjectsInCameraViewGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectDetectionResponse}
     */
    objectDetectionDetectObjectsInCameraViewGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'cameraIP': opts['cameraIP'],
        'imageSize': opts['imageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ObjectDetectionResponse;
      return this.apiClient.callApi(
        '/ObjectDetection/DetectObjectsInCameraView', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the objectDetectionGetDetectionImageGet operation.
     * @callback module:api/ObjectDetectionApi~objectDetectionGetDetectionImageGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.cameraIP 
     * @param {module:model/ImageSize} opts.imageSize 
     * @param {module:api/ObjectDetectionApi~objectDetectionGetDetectionImageGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    objectDetectionGetDetectionImageGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'cameraIP': opts['cameraIP'],
        'imageSize': opts['imageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/ObjectDetection/GetDetectionImage', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
