/**
 * ActionDetection.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DetectedObject model module.
 * @module model/DetectedObject
 * @version 1.0
 */
class DetectedObject {
    /**
     * Constructs a new <code>DetectedObject</code>.
     * @alias module:model/DetectedObject
     */
    constructor() { 
        
        DetectedObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DetectedObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DetectedObject} obj Optional instance to populate.
     * @return {module:model/DetectedObject} The populated <code>DetectedObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetectedObject();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('percentage_probability')) {
                obj['percentage_probability'] = ApiClient.convertToType(data['percentage_probability'], 'Number');
            }
            if (data.hasOwnProperty('box_points')) {
                obj['box_points'] = ApiClient.convertToType(data['box_points'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
DetectedObject.prototype['name'] = undefined;

/**
 * @member {Number} percentage_probability
 */
DetectedObject.prototype['percentage_probability'] = undefined;

/**
 * @member {Array.<Number>} box_points
 */
DetectedObject.prototype['box_points'] = undefined;






export default DetectedObject;

