/**
 * ActionDetection.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ActionDetectionApi);
  }
}(this, function(expect, ActionDetectionApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ActionDetectionApi.CameraApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CameraApi', function() {
    describe('cameraDetectObjectsInCameraViewGet', function() {
      it('should call cameraDetectObjectsInCameraViewGet successfully', function(done) {
        //uncomment below and update the code to test cameraDetectObjectsInCameraViewGet
        //instance.cameraDetectObjectsInCameraViewGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cameraGetDetectionImageGet', function() {
      it('should call cameraGetDetectionImageGet successfully', function(done) {
        //uncomment below and update the code to test cameraGetDetectionImageGet
        //instance.cameraGetDetectionImageGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cameraListGet', function() {
      it('should call cameraListGet successfully', function(done) {
        //uncomment below and update the code to test cameraListGet
        //instance.cameraListGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
