/**
 * ActionDetection.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DetectedObject from './model/DetectedObject';
import ImageSize from './model/ImageSize';
import ObjectDetectionResponse from './model/ObjectDetectionResponse';
import CameraApi from './api/CameraApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ActionDetectionApi = require('index'); // See note below*.
* var xxxSvc = new ActionDetectionApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ActionDetectionApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ActionDetectionApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ActionDetectionApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DetectedObject model constructor.
     * @property {module:model/DetectedObject}
     */
    DetectedObject,

    /**
     * The ImageSize model constructor.
     * @property {module:model/ImageSize}
     */
    ImageSize,

    /**
     * The ObjectDetectionResponse model constructor.
     * @property {module:model/ObjectDetectionResponse}
     */
    ObjectDetectionResponse,

    /**
    * The CameraApi service constructor.
    * @property {module:api/CameraApi}
    */
    CameraApi
};
